# Generated by Django 5.2.1 on 2025-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('artist', models.CharField(max_length=100, verbose_name='Artista')),
                ('album', models.CharField(max_length=100, verbose_name='Álbum')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('rating', models.IntegerField(verbose_name='Nota (1–5)')),
                ('album_cover_url', models.URLField(blank=True, null=True, verbose_name='Capa do Álbum (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
